[package]
name = "entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
sea-orm = { version = "0.7.1", default-features = false, features = [ "macros", "debug-print", "runtime-actix-native-tls", "sqlx-postgres"] }
